### PR TITLE
Updated `c-blosc` to commit 9dc93b1 and `zstd` to v1.5.2

### LINKED ISSUE #186: Build issue on macos12.6
Failed to build with macos12.6 on a x86_64 CPU, python3.10 with default build options.

First error:
```
clang: error: the clang compiler does not support '-march=native'
```
This option was apparently not available for clang on ARM before v15.0.0

Using `HDF5PLUGIN_NATIVE=False` fixes it error, but build fails later with:
```
src/c-blosc/blosc/bitshuffle-avx2.c:22:4: error: AVX2 is not supported by the target architecture/platform and/or this compiler.
...
```
This seems to be due to building fat library (`-arch arm64 -arch x86_64` options) with initial option detection being run only on host architecture.

### PR DESCRIPTION
**Pull request by t20100**
This PR updates `c-blosc` to commit 9dc93b1 initially to fix macos `universal2` build.
It also updates `zstd` to v1.5.2 which includes a piece of x86_64 assembly code (that looks to work by passing it as `extra_objects` to the `Extension`s).
This still needs testing on architecture different from x86_64.

closes #186

### CODE REVIEW

**Comment by t20100** [comment]
The assembly code is only enabled under linux and macos and explicitly disabled otherwise.
There is further checks with C macros to check if it is actually there.

Tested also on Power9 and macos ARM.

One issue may be for generic builds (manylinux, conda): This assembly code uses [BMI2](https://en.wikipedia.org/wiki/X86_Bit_manipulation_instruction_set#BMI2_(Bit_Manipulation_Instruction_Set_2)) instructions which are apparently available starting from [Haswell](https://en.wikipedia.org/wiki/Haswell_(microarchitecture)) Intel processors and [Excavator](https://en.wikipedia.org/wiki/Excavator_(microarchitecture)) AMD processors, so available since about 10 years.

**Comment by t20100** [comment]
I added an env. var. `HDF5PLUGIN_BMI2=True|False` (default `True`) to allow disabling this.

**Comment by t20100** [comment]
> I like the conservative approach concerning assembler code and windows

If you know how to handle assembly code in build through `setuptools` on Windows, I'd take it.

**Comment by t20100** [comment]
From a quick look (I haven't tested anything), Visual Studio does not seems to support assembly code by default.
From what I've seen, one need to install an extra tool like [nasm](https://www.nasm.us/) to compile the assembly code first.
With `gcc` and `clang`, one can pass the `.S` file directly at link time: thus the use of `extra_objects` in this PR and that I disabled it elsewhere including Windows.
We can consider enabling it for Windows when it is not using Visual Studio, but it is really a corner case and not worth the effort to me.
